2022-08-11 13:11:55,820:ERROR:neat:gen-mut-model failed, see the traceback below
Traceback (most recent call last):
  File "/Users/ralhazmy/Documents/NEAT/NEAT/neat/cli/cli.py", line 133, in main
    cmd(args)
  File "/Users/ralhazmy/Documents/NEAT/NEAT/neat/cli/commands/gen_mut_model.py", line 53, in execute
    compute_mut_runner(arguments.reference, arguments.mutations, arguments.bed, arguments.outcounts, arguments.show_trinuc,
  File "/Users/ralhazmy/Documents/NEAT/NEAT/neat/gen_mut_model/runner.py", line 561, in compute_mut_runner
    if not os.path.is_file(reference):
AttributeError: module 'posixpath' has no attribute 'is_file'
